### PR TITLE
Upgraded sample app

### PR DESCRIPTION
**Pull request by terryyoon-pdftron**
[NSDK-168](https://linear.app/pdftron/issue/NSDK-168/dev-update-pdftron-react-native-sample-app)

### Overview:

This PR replaces the sample app with a more comprehensive app in order to better demonstrate how the wrapper can be embedded in an existing app and how its API can be used.

The app is a simple file manager within the app's folder with the ability to add files from the device's local storage or from the web, plus other miscellaneous functionalities. It uses this package for opening PDF files and for converting Office files to PDF.

The app is built using Expo SDK 46 with bare workflow (ejected) and React Native version 0.69.4.

### Testing:

- Delete `node_modules`, and run `yarn install`
- Run the app:
    - iOS: `yarn ios`
    - Android: `yarn android`

### CODE REVIEW

**Comment by sgong-pdftron** [comment]
@darrenchann could you please perform first round of review, thanks.

**Comment by darrenchann** [comment]
Tried running project going through repro steps:
image

(tested rerunning project/rebuilding project on master branch with no issues)

**Comment by terryyoon-pdftron** [comment]
@darrenchann is that from this repo or the main React Native repo? the settings.gradle file looks different

**Comment by darrenchann** [comment]
> @darrenchann is that from this repo or the main React Native repo? the settings.gradle file looks different

Let me review my project structure, it's not looking correct on my end

**Comment by darrenchann** [comment]
iOS:
image

android:
image

now able to get both platforms up

**Review by darrenchann — APPROVED** [review]
was able to run new sample app with both platforms on ios/android on my end

**Pull request merged**
